### ISSUE TITLE
## FOUND-A-BUG

### ISSUE THREAD

**Issue by wisdombe** [Amiyahayadev/circle-12-quiz-app#4]
i answered the HTML section of your quiz app and after submitting the answers. i realized that some questions I checked and was sure I answered were unchecked themselves. i don't know why though. could be because of the device, because i was on a mobile phone in the instance i am describing. still worth checking out though

**Comment by Amiyahayadev** [comment]
Finally! Someone has noticed the bug. Thank you @wisdombe for reaching out. Yes I'm aware of the bug but was hoping someone could challenge themselves to fix it. It's not from your device, but from the index.html code. Apparently, it seems some tags were not closed properly, it could be any of the cases below. Would be grateful if you can challenge yourself and fix the bug!

- _**questions**_ and _**options**_ wrappers(div) not closed well
```
<div class="question">
     <div class="options">
     </div>
</div>  
```

OR 

- Label and input not connected properly
```
<label><input type="radio" name="q(no.)" value="a" /></label
```

**Comment by wisdombe** [comment]
Assign the issue to me , so I can work on it and fix it

**Comment by Amiyahayadev** [comment]
Great thanks a lot, just assigned it to you. @wisdombe , don't forget to create a branch for this issue

**Comment by wisdombe** [comment]
you're welcome . would you be interested in working on more projects together?

**Comment by Amiyahayadev** [comment]
Of course I am! I intend to dip deeper into Javascript by building some projects next semester, Are you an AltSchool student? Does't matter if you aren't thought. Let's connect via email. Thank you @wisdombe

**Comment by wisdombe** [comment]
ok and i am also an AltSchool student, frontend track. i will message you on Slack
